name: CI (nightly)

on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 1,15 * *" # Every 2 weeks, on 1st and 15th at 7:00 AM

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: nightly}
          - {os: macos-latest, crystal: nightly}
    runs-on: ${{matrix.os}}
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - uses: actions/checkout@v2
      - run: shards install --ignore-crystal-version
      - run: crystal spec --error-on-warnings --error-trace
